
<div class="signup-page" style="background-image: url(<?= $this->url->get("public/img/art.gif") ?>)">

    <div class="wrapper">
        <div class="header header-filter">

            <div class="container">

                <div class="row">
                    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-6">
                        <div class="card card-signup">
                            <form class="form" method="post" action="<?= $this->url->get("landing/inscription")?>">
                                <div class="header header-primary text-center">
                                    <h4>Sign Up</h4>
                                </div>
                                <p class="text-divider">Redéfinissons le Social</p>
                                <div class="content">
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">account_circle</i>
                                        </span>
                                        <div class="form-group is-empty"><input type="text" class="form-control" name="nom" placeholder="Nom..."><span class="material-input"></span></div>
                                    </div>

                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">account_circle</i>
                                        </span>
                                        <div class="form-group is-empty"><input type="text" class="form-control" name="prenom" placeholder="Prenom..."><span class="material-input"></span></div>
                                    </div>


                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">email</i>
                                        </span>
                                        <div class="form-group is-empty"><input type="text" class="form-control" name="email" placeholder="Email..."><span class="material-input"></span></div>
                                    </div>

                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">lock_outline</i>
                                        </span>
                                        <div class="form-group is-empty"><input type="password" placeholder="Mot de passe..." name="passwordHash" class="form-control"><span class="material-input"></span></div>
                                    </div>

                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="material-icons">lock_outline</i>
                                        </span>
                                        <div class="form-group is-empty"><input type="password" placeholder="Mot de passe..." name="cpassword" class="form-control"><span class="material-input"></span></div>
                                    </div>

    
                                    <div class="checkbox">
                                            <label>
                                                    <input type="checkbox" name="optionsCheckboxes" checked>
                                                    Remenber my password ?
                                            </label>
                                    </div>
                                </div>
                                <div class="footer text-center">
                                    <button type="submit" class="btn btn-simple btn-primary btn-lg">Get Started</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="http://www.creative-tim.com">
                                    Creative Tim
                                </a>
                            </li>
                            <li>
                                <a href="http://presentation.creative-tim.com">
                                    About Us
                                </a>
                            </li>
                            <li>
                                <a href="http://blog.creative-tim.com">
                                    Blog
                                </a>
                            </li>
                            <li>
                                <a href="http://www.creative-tim.com/license">
                                    Licenses
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div class="copyright pull-right">
                        © 2017, made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com" target="_blank">As-and Chanou</a>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</div>