<div class="profile-page">
    <nav class="navbar navbar-fixed-top navbar-color-on-scroll navbar-transparent">
        <div class="container" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example-navbar-transparent">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#pablo">Timeline</a>
        </div>

        <div class="collapse navbar-collapse" id="example-navbar-transparent">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#pablo">
                        <i class="fa fa-facebook-square"></i>Facebook
                    </a>
                </li>
                <li>
                    <a href="#pablo">
                        <i class="fa fa-twitter"></i>Twitter
                    </a>
                </li>
                <li>
                    <a href="#pablo">
                        <i class="fa fa-instagram"></i> Instagram
                    </a>
                </li>
            </ul>
        </div>
    </div>

</nav>
<div class="wrapper">
    <div class="header header-filter" style="background-image: url(<?= $this->url->get("public/img/bg2.jpeg") ?>);"></div>
</div>

    <div class="main main-raised">
        <div class="container">
            <div class="section text-center section-landing">

            </div>
        </div>

    </div>
</div>